kind: List
apiVersion: v1
items:
- kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: admin-role
    namespace: bastion-telco
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: cnf-ci
  roleRef:
    kind: ClusterRole
    apiGroup: rbac.authorization.k8s.io
    name: admin
